# -*- coding: utf-8 -*-
"""Customer Churn Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MsFwo484LvVvhPhHEliWJZvWGkuAwa8n
"""

!pip install gradio pandas numpy scikit-learn matplotlib seaborn -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gradio as gr
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, f1_score

def create_churn_data():
    """Generate synthetic customer churn dataset"""
    np.random.seed(42)
    n_customers = 1000

    data = {
        'Age': np.random.randint(18, 75, n_customers),
        'Tenure_Months': np.random.randint(0, 72, n_customers),
        'Monthly_Charges': np.random.uniform(20, 150, n_customers),
        'Total_Charges': np.random.uniform(100, 8000, n_customers),
        'Internet_Service': np.random.choice(['Fiber', 'DSL', 'No'], n_customers),
        'Contract_Type': np.random.choice(['Month-to-Month', 'One-Year', 'Two-Year'], n_customers),
        'Payment_Method': np.random.choice(['Credit Card', 'Bank Transfer', 'Check', 'Electronic'], n_customers),
        'Monthly_Usage_GB': np.random.uniform(0, 500, n_customers),
        'Support_Tickets': np.random.randint(0, 10, n_customers),
        'Premium_Support': np.random.choice([0, 1], n_customers),
    }

    df = pd.DataFrame(data)

    # Create target variable with realistic relationships
    churn_probability = (
        (df['Tenure_Months'] < 12) * 0.3 +
        (df['Contract_Type'] == 'Month-to-Month') * 0.25 +
        (df['Monthly_Charges'] > 100) * 0.2 +
        (df['Support_Tickets'] > 5) * 0.15 +
        (df['Premium_Support'] == 0) * 0.1
    )

    df['Churn'] = (np.random.random(n_customers) < churn_probability).astype(int)

    return df

df = create_churn_data()
print("Customer Dataset Created:")
print(df.head(10))
print(f"\nChurn Distribution:\n{df['Churn'].value_counts()}")

# Encode categorical variables
le_internet = LabelEncoder()
le_contract = LabelEncoder()
le_payment = LabelEncoder()

df_encoded = df.copy()
df_encoded['Internet_Service'] = le_internet.fit_transform(df['Internet_Service'])
df_encoded['Contract_Type'] = le_contract.fit_transform(df['Contract_Type'])
df_encoded['Payment_Method'] = le_payment.fit_transform(df['Payment_Method'])

# EDA Visualizations
fig, axes = plt.subplots(2, 3, figsize=(16, 10))

# Churn distribution
churn_counts = df['Churn'].value_counts()
colors = ['#2ecc71', '#e74c3c']
axes[0, 0].pie(churn_counts.values, labels=['Retained', 'Churned'],
               autopct='%1.1f%%', colors=colors, startangle=90)
axes[0, 0].set_title('Customer Churn Distribution', fontweight='bold')

# Tenure vs Churn
tenure_churn = df.groupby('Tenure_Months')['Churn'].mean()
axes[0, 1].plot(tenure_churn.index, tenure_churn.values * 100, linewidth=2, color='#3498db')
axes[0, 1].set_xlabel('Tenure (Months)')
axes[0, 1].set_ylabel('Churn Rate (%)')
axes[0, 1].set_title('Churn Rate vs Tenure', fontweight='bold')
axes[0, 1].grid(True, alpha=0.3)

# Monthly Charges vs Churn
axes[0, 2].scatter(df[df['Churn']==0]['Monthly_Charges'],
                  [0]*len(df[df['Churn']==0]), alpha=0.5, label='Retained')
axes[0, 2].scatter(df[df['Churn']==1]['Monthly_Charges'],
                  [1]*len(df[df['Churn']==1]), alpha=0.5, label='Churned')
axes[0, 2].set_xlabel('Monthly Charges ($)')
axes[0, 2].set_ylabel('Churn')
axes[0, 2].set_title('Monthly Charges vs Churn', fontweight='bold')
axes[0, 2].legend()
axes[0, 2].set_yticks([0, 1])

# Contract Type vs Churn
contract_churn = df.groupby('Contract_Type')['Churn'].mean() * 100
axes[1, 0].bar(contract_churn.index, contract_churn.values, color=['#f39c12', '#9b59b6', '#2ecc71'])
axes[1, 0].set_ylabel('Churn Rate (%)')
axes[1, 0].set_title('Churn by Contract Type', fontweight='bold')
axes[1, 0].tick_params(axis='x', rotation=45)

# Support Tickets vs Churn
axes[1, 1].scatter(df['Support_Tickets'], df['Churn'], alpha=0.4)
axes[1, 1].set_xlabel('Support Tickets')
axes[1, 1].set_ylabel('Churn (0=No, 1=Yes)')
axes[1, 1].set_title('Support Tickets vs Churn', fontweight='bold')
axes[1, 1].grid(True, alpha=0.3)

# Age vs Churn
age_churn = df.groupby(pd.cut(df['Age'], bins=10))['Churn'].mean() * 100
axes[1, 2].bar(range(len(age_churn)), age_churn.values, color='#1abc9c')
axes[1, 2].set_xlabel('Age Group')
axes[1, 2].set_ylabel('Churn Rate (%)')
axes[1, 2].set_title('Churn by Age Group', fontweight='bold')

plt.tight_layout()
plt.savefig('churn_eda.png', dpi=100, bbox_inches='tight')
plt.show()

feature_cols = ['Age', 'Tenure_Months', 'Monthly_Charges', 'Total_Charges',
                'Internet_Service', 'Contract_Type', 'Payment_Method',
                'Monthly_Usage_GB', 'Support_Tickets', 'Premium_Support']
X = df_encoded[feature_cols]
y = df_encoded['Churn']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=10)
model.fit(X_train, y_train)

# Predictions
y_pred_test = model.predict(X_test)
y_pred_proba_test = model.predict_proba(X_test)[:, 1]

# Evaluation metrics
accuracy = model.score(X_test, y_test)
roc_auc = roc_auc_score(y_test, y_pred_proba_test)
f1 = f1_score(y_test, y_pred_test)

print("\n" + "="*50)
print("MODEL EVALUATION METRICS")
print("="*50)
print(f"Accuracy: {accuracy:.4f}")
print(f"ROC-AUC Score: {roc_auc:.4f}")
print(f"F1 Score: {f1:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_test, target_names=['Retained', 'Churned']))
print("="*50)

# Feature importance
feature_importance = pd.DataFrame({
    'Feature': feature_cols,
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)

print("\nTop Features:")
print(feature_importance.head(10))

def predict_churn(age, tenure, monthly_charges, total_charges, internet_service,
                  contract_type, payment_method, monthly_usage, support_tickets, premium_support):
    """
    Predict customer churn
    """
    try:
        # Validation
        if not (18 <= age <= 100):
            return "Error: Age must be between 18-100", None

        if tenure < 0 or tenure > 72:
            return "Error: Tenure must be 0-72 months", None

        if monthly_charges <= 0:
            return "Error: Monthly charges must be positive", None

        # Encode categorical variables
        internet_encoded = list(le_internet.classes_).index(internet_service)
        contract_encoded = list(le_contract.classes_).index(contract_type)
        payment_encoded = list(le_payment.classes_).index(payment_method)

        # Prepare input
        input_data = np.array([[
            age, tenure, monthly_charges, total_charges,
            internet_encoded, contract_encoded, payment_encoded,
            monthly_usage, support_tickets, premium_support
        ]])

        # Make prediction
        churn_pred = model.predict(input_data)[0]
        churn_prob = model.predict_proba(input_data)[0][1] * 100

        # Create visualization
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        # Churn probability gauge
        color = '#e74c3c' if churn_prob > 50 else '#f39c12' if churn_prob > 30 else '#2ecc71'

        axes[0].barh(['Churn Risk'], [churn_prob], color=color, height=0.5)
        axes[0].barh(['Safe'], [100-churn_prob], left=[churn_prob], color='lightgray', height=0.5, alpha=0.3)
        axes[0].set_xlim(0, 100)
        axes[0].set_title('Churn Risk Assessment', fontweight='bold', fontsize=12)
        axes[0].text(churn_prob/2, 0, f'{churn_prob:.1f}%',
                    ha='center', va='center', fontsize=14, fontweight='bold', color='white')
        axes[0].set_xlabel('Risk Level (%)')

        # Customer profile
        profile_data = {
            'Metric': ['Age', 'Tenure', 'Monthly\nCharges', 'Usage\n(GB)', 'Support\nTickets'],
            'Value': [age, tenure, f'${monthly_charges:.0f}', f'{monthly_usage:.0f}', support_tickets]
        }

        axes[1].axis('off')
        table_data = [[f"{profile_data['Metric'][i]}: {profile_data['Value'][i]}"]
                     for i in range(len(profile_data['Metric']))]

        customer_info = f"""
        CUSTOMER PROFILE:
        • Age: {age} years
        • Tenure: {tenure} months
        • Monthly Charges: ${monthly_charges:.2f}
        • Total Charges: ${total_charges:.2f}
        • Internet Service: {internet_service}
        • Contract Type: {contract_type}
        • Monthly Usage: {monthly_usage:.0f} GB
        • Support Tickets: {support_tickets}
        • Premium Support: {"Yes" if premium_support else "No"}
        """

        axes[1].text(0.1, 0.5, customer_info, fontsize=11, family='monospace',
                    verticalalignment='center', bbox=dict(boxstyle='round',
                    facecolor='wheat', alpha=0.5))

        plt.tight_layout()
        plt.savefig('churn_prediction.png', dpi=100, bbox_inches='tight')
        plt.close()

        # Prepare report
        if churn_prob > 60:
            risk_category = "🔴 HIGH RISK"
            recommendation = """
            ⚠️ URGENT ACTION REQUIRED:
            • Offer special retention discount
            • Assign dedicated customer success manager
            • Provide premium support
            • Consider loyalty program
            • Schedule follow-up call immediately
            """
        elif churn_prob > 40:
            risk_category = "🟡 MEDIUM RISK"
            recommendation = """
            ⚠️ ACTION RECOMMENDED:
            • Monitor customer closely
            • Offer contract upgrade incentives
            • Ensure proactive customer support
            • Personalize service offerings
            • Check in quarterly
            """
        else:
            risk_category = "🟢 LOW RISK"
            recommendation = """
            ✅ STANDARD MANAGEMENT:
            • Maintain regular service quality
            • Periodic satisfaction surveys
            • Standard support response
            • Continue current engagement
            • Monitor for changes
            """

        report = f"""
        🎯 CHURN PREDICTION ANALYSIS
        {'='*50}

        🔮 PREDICTION: {risk_category}
        Churn Probability: {churn_prob:.2f}%

        {'='*50}
        📋 CUSTOMER DETAILS:
        • Age: {age} years
        • Tenure: {tenure} months
        • Monthly Charges: ${monthly_charges:.2f}
        • Internet Service: {internet_service}
        • Contract Type: {contract_type}
        • Support Tickets: {support_tickets}

        {'='*50}
        💡 RECOMMENDATIONS:
        {recommendation}

        ✅ Analysis complete!
        {'='*50}
        """

        return report, "churn_prediction.png"

    except Exception as e:
        return f"Error: {str(e)}", None

# Create Gradio Interface
with gr.Blocks(theme=gr.themes.Soft(), title="Customer Churn Prediction") as demo:
    gr.Markdown("""
    # 👥 Customer Churn Prediction System
    ### Predict & Prevent Customer Attrition

    This system uses **Random Forest Classification** to identify customers at risk of churning,
    enabling proactive retention strategies.
    """)

    with gr.Row():
        with gr.Column():
            gr.Markdown("### 👤 Customer Information")

            age = gr.Slider(
                minimum=18, maximum=80, value=45, step=1,
                label="Age (years)",
                info="Customer age in years"
            )

            tenure = gr.Slider(
                minimum=0, maximum=72, value=24, step=1,
                label="Tenure (months)",
                info="How long customer has been with company"
            )

            monthly_charges = gr.Slider(
                minimum=20, maximum=150, value=75, step=5,
                label="Monthly Charges ($)",
                info="Monthly service charges"
            )

            total_charges = gr.Slider(
                minimum=0, maximum=10000, value=2000, step=100,
                label="Total Charges ($)",
                info="Total accumulated charges"
            )

            gr.Markdown("### 🔧 Service Information")

            internet_service = gr.Dropdown(
                choices=['Fiber', 'DSL', 'No'],
                value='DSL',
                label="Internet Service Type"
            )

            contract_type = gr.Dropdown(
                choices=['Month-to-Month', 'One-Year', 'Two-Year'],
                value='One-Year',
                label="Contract Type"
            )

            payment_method = gr.Dropdown(
                choices=['Credit Card', 'Bank Transfer', 'Check', 'Electronic'],
                value='Credit Card',
                label="Payment Method"
            )

            monthly_usage = gr.Slider(
                minimum=0, maximum=500, value=100, step=10,
                label="Monthly Usage (GB)",
                info="Average monthly data usage"
            )

            support_tickets = gr.Slider(
                minimum=0, maximum=10, value=2, step=1,
                label="Support Tickets",
                info="Number of support tickets filed"
            )

            premium_support = gr.Checkbox(
                value=False,
                label="Premium Support Active"
            )

            predict_btn = gr.Button("🔍 Predict Churn Risk",
                                   size="lg", variant="primary")

        with gr.Column():
            gr.Markdown("### 📊 Model Information")
            gr.Markdown(f"""
            - **Algorithm**: Random Forest Classifier
            - **Training Samples**: {len(X_train)}
            - **Test Samples**: {len(X_test)}
            - **Model Accuracy**: {accuracy:.4f}
            - **ROC-AUC Score**: {roc_auc:.4f}
            - **F1 Score**: {f1:.4f}

            **Top Risk Factors:**
            """)

            for idx, row in feature_importance.head(5).iterrows():
                feature_name = row['Feature'].replace('_', ' ')
                importance_pct = row['Importance'] * 100
                gr.Markdown(f"• **{feature_name}**: {importance_pct:.1f}%")

    gr.Markdown("---")

    with gr.Row():
        with gr.Column():
            output_report = gr.Textbox(
                label="📋 Churn Analysis Report",
                lines=15,
                max_lines=20,
                interactive=False
            )

        with gr.Column():
            output_chart = gr.Image(
                label="📊 Risk Visualization",
                type="filepath"
            )

    predict_btn.click(
        fn=predict_churn,
        inputs=[age, tenure, monthly_charges, total_charges, internet_service,
               contract_type, payment_method, monthly_usage, support_tickets, premium_support],
        outputs=[output_report, output_chart]
    )

demo.launch(share=True)

