# -*- coding: utf-8 -*-
"""Student Performance Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K8IlyLTdDbv_kDIByBOAqjwTga7-taqV
"""

!pip install gradio pandas numpy scikit-learn matplotlib seaborn -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import gradio as gr
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

def create_student_data():
    """Generate synthetic student performance dataset"""
    np.random.seed(42)
    n_students = 500

    data = {
        'Study_Hours': np.random.uniform(2, 12, n_students),
        'Attendance': np.random.uniform(50, 100, n_students),
        'Previous_Score': np.random.uniform(40, 95, n_students),
        'Assignment_Score': np.random.uniform(30, 100, n_students),
        'Gender': np.random.choice(['Male', 'Female'], n_students)
    }

    df = pd.DataFrame(data)

    # Create target variable with realistic relationship
    df['Final_Marks'] = (
        df['Study_Hours'] * 5 +
        df['Attendance'] * 0.3 +
        df['Previous_Score'] * 0.4 +
        df['Assignment_Score'] * 0.3 +
        np.random.normal(0, 5, n_students)  # Add noise
    )

    df['Final_Marks'] = df['Final_Marks'].clip(0, 100)
    return df

df = create_student_data()
print("Student Dataset Created:")
print(df.head(10))
print(f"\nDataset Info:\n{df.info()}")

df_encoded = df.copy()
df_encoded['Gender'] = df_encoded['Gender'].map({'Male': 0, 'Female': 1})
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
corr_matrix = df_encoded.corr()
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            ax=axes[0, 0], cbar_kws={'label': 'Correlation'})
axes[0, 0].set_title('Feature Correlation Matrix', fontweight='bold')

# Study Hours vs Final Marks
axes[0, 1].scatter(df['Study_Hours'], df['Final_Marks'], alpha=0.6, s=50)
axes[0, 1].set_xlabel('Study Hours')
axes[0, 1].set_ylabel('Final Marks')
axes[0, 1].set_title('Study Hours vs Final Marks', fontweight='bold')
axes[0, 1].grid(True, alpha=0.3)

# Attendance vs Final Marks
axes[0, 2].scatter(df['Attendance'], df['Final_Marks'], alpha=0.6, s=50, color='orange')
axes[0, 2].set_xlabel('Attendance (%)')
axes[0, 2].set_ylabel('Final Marks')
axes[0, 2].set_title('Attendance vs Final Marks', fontweight='bold')
axes[0, 2].grid(True, alpha=0.3)

# Distribution of Final Marks
axes[1, 0].hist(df['Final_Marks'], bins=30, color='skyblue', edgecolor='black')
axes[1, 0].set_xlabel('Final Marks')
axes[1, 0].set_ylabel('Frequency')
axes[1, 0].set_title('Distribution of Final Marks', fontweight='bold')

# Assignment Score vs Final Marks
axes[1, 1].scatter(df['Assignment_Score'], df['Final_Marks'], alpha=0.6, s=50, color='green')
axes[1, 1].set_xlabel('Assignment Score')
axes[1, 1].set_ylabel('Final Marks')
axes[1, 1].set_title('Assignment Score vs Final Marks', fontweight='bold')
axes[1, 1].grid(True, alpha=0.3)

# Previous Score vs Final Marks
axes[1, 2].scatter(df['Previous_Score'], df['Final_Marks'], alpha=0.6, s=50, color='red')
axes[1, 2].set_xlabel('Previous Score')
axes[1, 2].set_ylabel('Final Marks')
axes[1, 2].set_title('Previous Score vs Final Marks', fontweight='bold')
axes[1, 2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('student_eda.png', dpi=100, bbox_inches='tight')
plt.show()

X = df_encoded[['Study_Hours', 'Attendance', 'Previous_Score', 'Assignment_Score', 'Gender']]
y = df_encoded['Final_Marks']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Random Forest
model = RandomForestRegressor(n_estimators=100, random_state=42, max_depth=10)
model.fit(X_train, y_train)

# Predictions
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test, y_pred_test)
mse = mean_squared_error(y_test, y_pred_test)
r2 = r2_score(y_test, y_pred_test)

print("\n" + "="*50)
print("MODEL EVALUATION METRICS")
print("="*50)
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"R² Score: {r2:.4f}")
print("="*50)

# Feature Importance
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance['Feature'], feature_importance['Importance'], color='skyblue')
plt.xlabel('Importance Score')
plt.title('Feature Importance for Student Performance', fontweight='bold')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=100, bbox_inches='tight')
plt.show()

def predict_student_performance(study_hours, attendance, previous_score, assignment_score, gender):
    """
    Predict student's final marks based on input features
    """
    try:
        # Validation
        if not all(isinstance(x, (int, float)) for x in [study_hours, attendance, previous_score, assignment_score]):
            return "Error: Please enter valid numbers", None

        if not (0 <= attendance <= 100):
            return "Error: Attendance must be between 0-100%", None

        if not (0 <= previous_score <= 100):
            return "Error: Previous score must be between 0-100", None

        if not (0 <= assignment_score <= 100):
            return "Error: Assignment score must be between 0-100", None

        if not (0 <= study_hours <= 24):
            return "Error: Study hours must be between 0-24", None

        # Encode gender
        gender_encoded = 1 if gender == "Male" else 0

        # Prepare input
        input_data = np.array([[study_hours, attendance, previous_score, assignment_score, gender_encoded]])

        # Make prediction
        predicted_marks = model.predict(input_data)[0]
        predicted_marks = max(0, min(100, predicted_marks))  # Clip to 0-100

        # Determine performance category
        if predicted_marks >= 80:
            category = "🌟 EXCELLENT"
            color = "#28a745"
        elif predicted_marks >= 60:
            category = "✅ GOOD"
            color = "#17a2b8"
        elif predicted_marks >= 40:
            category = "⚠️ AVERAGE"
            color = "#ffc107"
        else:
            category = "❌ NEEDS IMPROVEMENT"
            color = "#dc3545"

        # Create visualization
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        # Gauge chart (score distribution)
        axes[0].barh(['Your Prediction'], [predicted_marks], color=color, height=0.5)
        axes[0].barh(['Max Score'], [100], color='lightgray', height=0.5, alpha=0.3)
        axes[0].set_xlim(0, 100)
        axes[0].set_xlabel('Marks', fontsize=12)
        axes[0].set_title('Predicted Final Marks', fontweight='bold', fontsize=12)
        axes[0].text(predicted_marks/2, 0, f'{predicted_marks:.1f}',
                    ha='center', va='center', fontsize=16, fontweight='bold', color='white')

        # Input features bar chart
        features = ['Study Hours\n(normalized)', 'Attendance\n(%)', 'Previous\nScore', 'Assignment\nScore']
        values = [
            (study_hours / 12) * 100,  # Normalize to 0-100
            attendance,
            previous_score,
            assignment_score
        ]

        bars = axes[1].bar(features, values, color=['#3498db', '#e74c3c', '#2ecc71', '#f39c12'])
        axes[1].set_ylabel('Score / Percentage', fontsize=12)
        axes[1].set_title('Input Features Analysis', fontweight='bold', fontsize=12)
        axes[1].set_ylim(0, 100)
        axes[1].grid(axis='y', alpha=0.3)

        # Add value labels on bars
        for bar in bars:
            height = bar.get_height()
            axes[1].text(bar.get_x() + bar.get_width()/2., height,
                        f'{height:.1f}', ha='center', va='bottom', fontweight='bold')

        plt.tight_layout()
        plt.savefig('prediction_result.png', dpi=100, bbox_inches='tight')
        plt.close()

        # Prepare detailed report
        report = f"""
        📊 STUDENT PERFORMANCE PREDICTION REPORT
        {'='*50}

        📈 PREDICTED FINAL MARKS: {predicted_marks:.2f}/100
        📌 PERFORMANCE CATEGORY: {category}

        {'='*50}
        📋 INPUT ANALYSIS:
        • Study Hours: {study_hours:.2f} hours/week
        • Attendance: {attendance:.2f}%
        • Previous Score: {previous_score:.2f}/100
        • Assignment Score: {assignment_score:.2f}/100
        • Gender: {gender}

        {'='*50}
        🎯 RECOMMENDATIONS:
        """

        if predicted_marks < 40:
            report += """
        ⚠️ URGENT: Your performance needs immediate improvement!
        • Increase study hours significantly
        • Improve attendance to at least 80%
        • Focus on assignment quality
        • Consider tutoring support
            """
        elif predicted_marks < 60:
            report += """
        ⚠️ Action needed to improve performance:
        • Increase study hours to 6-8 hours/week
        • Maintain attendance above 85%
        • Complete all assignments on time
        • Practice previous year papers
            """
        elif predicted_marks < 80:
            report += """
        ✅ Good performance! Keep it up:
        • Maintain consistent study routine
        • Continue with regular attendance
        • Review and strengthen weak topics
        • Aim for excellence in the final push
            """
        else:
            report += """
        🌟 EXCELLENT! Outstanding performance:
        • Maintain your study discipline
        • Help other students (peer learning)
        • Explore advanced topics in the subject
        • You're on track for top grades!
            """

        report += f"\n{'='*50}\n✅ Prediction generated successfully!\n"

        return report, "prediction_result.png"

    except Exception as e:
        return f"Error: {str(e)}", None

with gr.Blocks(theme=gr.themes.Soft(), title="Student Performance Predictor") as demo:
    gr.Markdown("""
    # 🎓 Student Performance Predictor
    ### AI-Powered Academic Performance Analysis

    This system uses **Machine Learning** to predict a student's final marks based on:
    - Study hours
    - Attendance percentage
    - Previous exam scores
    - Assignment scores
    """)

    with gr.Row():
        with gr.Column():
            gr.Markdown("### 📝 Student Information")
            study_hours = gr.Slider(
                minimum=0, maximum=12, value=5, step=0.5,
                label="Study Hours per Week",
                info="Average hours spent studying per week"
            )

            attendance = gr.Slider(
                minimum=0, maximum=100, value=75, step=1,
                label="Attendance (%)",
                info="Percentage of classes attended"
            )

            previous_score = gr.Slider(
                minimum=0, maximum=100, value=60, step=1,
                label="Previous Exam Score",
                info="Score from previous exams (0-100)"
            )

            assignment_score = gr.Slider(
                minimum=0, maximum=100, value=65, step=1,
                label="Assignment Score",
                info="Average score on assignments (0-100)"
            )

            gender = gr.Radio(
                choices=["Male", "Female"],
                value="Male",
                label="Gender"
            )

            predict_btn = gr.Button("🚀 Predict Performance",
                                   size="lg", variant="primary")

        with gr.Column():
            gr.Markdown("### 📊 Model Information")
            gr.Markdown(f"""
            - **Algorithm**: Random Forest Regressor
            - **Training Samples**: {len(X_train)}
            - **Test Samples**: {len(X_test)}
            - **Model Accuracy (R²)**: {r2:.4f}
            - **Mean Absolute Error**: {mae:.2f} marks

            **Top Factors Affecting Performance:**
            """)

            for idx, row in feature_importance.iterrows():
                feature_name = row['Feature'].replace('_', ' ')
                importance_pct = row['Importance'] * 100
                gr.Markdown(f"• **{feature_name}**: {importance_pct:.1f}%")

    gr.Markdown("---")

    with gr.Row():
        with gr.Column():
            output_report = gr.Textbox(
                label="📋 Detailed Prediction Report",
                lines=15,
                max_lines=20,
                interactive=False
            )

        with gr.Column():
            output_chart = gr.Image(
                label="📊 Performance Visualization",
                type="filepath"
            )

    predict_btn.click(
        fn=predict_student_performance,
        inputs=[study_hours, attendance, previous_score, assignment_score, gender],
        outputs=[output_report, output_chart]
    )

demo.launch(share=True)

