# -*- coding: utf-8 -*-
"""Sales Forecasting System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SyWC1087Nsiv7zloup3GnKdK1DxHAhFU
"""

!pip install gradio pandas numpy scikit-learn matplotlib seaborn xgboost pyngrok -q

import pandas as pd
import numpy as np
from datetime import datetime , timedelta
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

url = "https://gist.githubusercontent.com/khanusama20/ee33c2869dd5cf3cebdf020be1ca43f6/raw/sales_sample_2024.csv"

df = pd.read_csv(url)

print(df.head())
print(df.shape)

df['sales_date'] = pd.to_datetime(df['sales_date'])
df = df.sort_values('sales_date').reset_index(drop=True)

df.isnull().sum()

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Convert date
df['sales_date'] = pd.to_datetime(df['sales_date'])

# Sort data
df = df.sort_values('sales_date').reset_index(drop=True)

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Remove duplicates
df = df.drop_duplicates()

# Create plots
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# 1. Sales Trend
axes[0, 0].plot(
    df['sales_date'],
    df['sales_amount'],
    linewidth=2
)
axes[0, 0].set_title(
    'Sales Trend Over Time',
    fontsize=12,
    fontweight='bold'
)
axes[0, 0].set_xlabel('Date')
axes[0, 0].set_ylabel('Sales Amount')
axes[0, 0].grid(True, alpha=0.3)


# 2. Daily Sales Distribution
axes[0, 1].hist(
    df['sales_amount'],
    bins=30
)
axes[0, 1].set_title(
    'Sales Amount Distribution',
    fontsize=12,
    fontweight='bold'
)
axes[0, 1].set_xlabel('Sales Amount')
axes[0, 1].set_ylabel('Frequency')
axes[0, 1].grid(True, alpha=0.3)


# 3. Monthly Sales
df['YearMonth'] = df['sales_date'].dt.to_period('M')

monthly_sales = (
    df.groupby('YearMonth')['sales_amount']
    .sum()
)

axes[1, 0].bar(
    range(len(monthly_sales)),
    monthly_sales.values
)

axes[1, 0].set_title(
    'Monthly Sales',
    fontsize=12,
    fontweight='bold'
)
axes[1, 0].set_xlabel('Month')
axes[1, 0].set_ylabel('Sales Amount')
axes[1, 0].grid(True, alpha=0.3)


# 4. Monthly Average Sales
monthly_avg = (
    df.groupby('YearMonth')['sales_amount']
    .mean()
)

axes[1, 1].plot(
    range(len(monthly_avg)),
    monthly_avg.values,
    marker='o'
)

axes[1, 1].set_title(
    'Average Monthly Sales',
    fontsize=12,
    fontweight='bold'
)
axes[1, 1].set_xlabel('Month')
axes[1, 1].set_ylabel('Average Sales')
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

plt.tight_layout()
plt.savefig('eda_plots.png', dpi=100, bbox_inches='tight')
plt.show()

daily_sales = df[['sales_date', 'sales_amount']].copy()

daily_sales = daily_sales.rename(columns={
    'sales_date': 'Date',
    'sales_amount': 'Sales'
})

daily_sales['Year'] = daily_sales['Date'].dt.year
daily_sales['Month'] = daily_sales['Date'].dt.month
daily_sales['Day'] = daily_sales['Date'].dt.day
daily_sales['DayOfWeek'] = daily_sales['Date'].dt.dayofweek
daily_sales['Quarter'] = daily_sales['Date'].dt.quarter
daily_sales['WeekOfYear'] = (
    daily_sales['Date'].dt.isocalendar().week.astype(int)
)

# Lag features
daily_sales['Sales_Lag1'] = daily_sales['Sales'].shift(1)
daily_sales['Sales_Lag7'] = daily_sales['Sales'].shift(7)
daily_sales['Sales_Lag30'] = daily_sales['Sales'].shift(30)

# Moving averages
daily_sales['MA7'] = (
    daily_sales['Sales']
    .rolling(7)
    .mean()
)

daily_sales['MA30'] = (
    daily_sales['Sales']
    .rolling(30)
    .mean()
)

daily_sales = daily_sales.dropna().reset_index(drop=True)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import math

# Prepare features and target
feature_columns = ['Year', 'Month', 'Day', 'DayOfWeek', 'Quarter',
                   'WeekOfYear', 'Sales_Lag1', 'Sales_Lag7', 'Sales_Lag30',
                   'MA7', 'MA30']
X = daily_sales[feature_columns]
y = daily_sales['Sales']
split_index = int(len(daily_sales) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = rf_model.score(X_test, y_test)

print(f"MAE: ${mae:.2f}")
print(f"RMSE: ${rmse:.2f}")
print(f"R²: {r2:.4f}")

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
plt.plot(y_test.values, label='Actual Sales', linewidth=2, marker='o')
plt.plot(y_pred_test, label='Predicted Sales', linewidth=2, marker='s', alpha=0.7)
plt.title('Actual vs Predicted Sales (Test Set)', fontsize=12, fontweight='bold')
plt.xlabel('Sample Index')
plt.ylabel('Sales Amount ($)')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.scatter(y_test.values, y_pred_test, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         'r--', lw=2, label='Prediction')
plt.title('Predicted vs Actual Values', fontsize=12, fontweight='bold')
plt.xlabel('Actual Sales')
plt.ylabel('Predicted Sales')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('model_performance.png', dpi=100, bbox_inches='tight')
plt.show()

def predict_future_sales(days_ahead=30):
    """Predict sales for next N days"""
    last_date = daily_sales['Date'].max()
    future_dates = pd.date_range(start=last_date + timedelta(days=1),
                                  periods=days_ahead, freq='D')

    predictions = []
    last_sales = daily_sales['Sales'].values[-1]

    for date in future_dates:
        feature_dict = {
            'Year': date.year,
            'Month': date.month,
            'Day': date.day,
            'DayOfWeek': date.dayofweek,
            'Quarter': date.quarter,
            'WeekOfYear': date.isocalendar()[1],
            'Sales_Lag1': last_sales,
            'Sales_Lag7': daily_sales['Sales'].values[-7] if len(daily_sales) > 7 else last_sales,
            'Sales_Lag30': daily_sales['Sales'].values[-30] if len(daily_sales) > 30 else last_sales,
            'MA7': daily_sales['MA7'].values[-1],
            'MA30': daily_sales['MA30'].values[-1]
        }

        X_future = pd.DataFrame([feature_dict])
        pred = rf_model.predict(X_future)[0]
        predictions.append({'Date': date, 'Predicted_Sales': pred})
        last_sales = pred

    return pd.DataFrame(predictions)

# Get future predictions
future_predictions = predict_future_sales(days_ahead=30)
print("\nFuture Sales Predictions (Next 30 Days):")
print(future_predictions.head(10))

import gradio as gr
from datetime import datetime

def forecast_interface(days_to_predict):
    """
    Gradio interface function for sales forecasting
    """
    try:
        # Validate input
        if not isinstance(days_to_predict, (int, float)) or days_to_predict <= 0:
            return "Error: Please enter a positive number of days", None

        days_to_predict = int(days_to_predict)

        if days_to_predict > 365:
            return "Error: Cannot predict more than 365 days ahead", None

        # Generate predictions
        predictions = predict_future_sales(days_ahead=days_to_predict)

        # Create visualization
        plt.figure(figsize=(14, 6))

        # Historical data
        plt.plot(daily_sales['Date'], daily_sales['Sales'],
                label='Historical Sales', linewidth=2, color='blue')

        # Predictions
        plt.plot(predictions['Date'], predictions['Predicted_Sales'],
                label='Forecasted Sales', linewidth=2, color='red',
                linestyle='--', marker='o')

        plt.title(f'Sales Forecast for Next {days_to_predict} Days',
                 fontsize=14, fontweight='bold')
        plt.xlabel('Date', fontsize=12)
        plt.ylabel('Sales Amount ($)', fontsize=12)
        plt.legend(fontsize=11)
        plt.grid(True, alpha=0.3)
        plt.xticks(rotation=45)
        plt.tight_layout()

        # Save plot
        plt.savefig('forecast_plot.png', dpi=100, bbox_inches='tight')
        plt.close()

        # Prepare summary statistics
        summary = f"""
        SALES FORECAST
        {'='*50}
        Period: Next {days_to_predict} days
        Date Range: {predictions['Date'].min().date()} to {predictions['Date'].max().date()}

        PREDICTIONS STATISTICS:
        Average Forecasted Sales: ${predictions['Predicted_Sales'].mean():.2f}
        Max Predicted Sales: ${predictions['Predicted_Sales'].max():.2f}
        Min Predicted Sales: ${predictions['Predicted_Sales'].min():.2f}

        MODEL PERFORMANCE:
        MAE: ${mae:.2f}
        RMSE: ${rmse:.2f}
        R² Score: {r2:.4f}

        Prediction
        """

        return summary, "forecast_plot.png"

    except Exception as e:
        return f"Error: {str(e)}", None

with gr.Blocks(theme=gr.themes.Soft(), title="Sales Forecasting System") as demo:
    gr.Markdown("""
    # Sales Forecasting System
    ### AI-Powered Sales Prediction

    This system uses **Random Forest Machine Learning** to predict future sales trends
    based on historical data, seasonal patterns, and time-series features.
    """)

    with gr.Row():
        with gr.Column():
            gr.Markdown("###Configuration")
            days_input = gr.Slider(
                minimum=1,
                maximum=365,
                value=30,
                step=1,
                label="Days to Forecast",
                info="Select how many days ahead you want to predict"
            )

            predict_btn = gr.Button("Generate Forecast",
                                   size="lg", variant="primary")

        with gr.Column():
            gr.Markdown("### 📈 Model Information")
            gr.Markdown(f"""
            - **Algorithm**: Random Forest Regressor
            - **Training Samples**: {len(X_train)}
            - **Test Samples**: {len(X_test)}
            - **Features Used**: {len(feature_columns)}
            - **Model Accuracy (R²)**: {r2:.4f}
            """)

    gr.Markdown("---")

    with gr.Row():
        with gr.Column():
            output_text = gr.Textbox(
                label="Forecast Summary",
                lines=12,
                max_lines=20,
                interactive=False
            )

        with gr.Column():
            output_plot = gr.Image(
                label="Forecast Visualized",
                type="filepath"
            )

    predict_btn.click(
        fn=forecast_interface,
        inputs=[days_input],
        outputs=[output_text, output_plot]
    )

    # Add example predictions tab
    with gr.Row():
        gr.Markdown("###Predictions")
        predictions_table = gr.Dataframe(
            value=future_predictions.head(15),
            label="Next 15 Days Forecast"
        )

# Launch the app
print("\n" + "="*50)
print("🚀 LAUNCHING GRADIO INTERFACE")
print("="*50)
demo.launch(share=True)



